import Link from "next/link";
import type { Metadata } from "next";
import { ArrowRight, ExternalLink, MessageSquare } from "lucide-react";
import { fapi } from "@/lib/api/server";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { InvestigationRow } from "@/lib/api/types";

export const metadata: Metadata = { title: "Pitches" };

export default async function PitchesPage() {
  const all = (await fapi.recentInvestigations(50)) ?? [];
  // The Investigation row stores `pitch_md` inline once drafted, so the
  // pitches list is just a filter over recent investigations — no new
  // endpoint needed.
  const withPitch = all.filter((r) => r.pitch_md && r.pitch_md.trim().length > 0);

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 sm:py-10">
      <header className="mb-6">
        <p className="flex items-center gap-2 text-xs uppercase tracking-wide text-muted-foreground">
          <MessageSquare className="size-3.5" />
          Pitches
        </p>
        <h1 className="mt-1 text-3xl font-semibold tracking-tight">
          Comments you&apos;ve drafted
        </h1>
        <p className="mt-2 max-w-2xl text-muted-foreground">
          Every pitch generated by the Pitch Writer. Open one to preview,
          copy-paste, or regenerate with a different tone.
        </p>
      </header>

      {withPitch.length === 0 ? (
        <Card className="border-border/60">
          <CardHeader className="space-y-3 text-center">
            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary">
              <MessageSquare className="size-6" />
            </div>
            <CardTitle className="text-2xl">No pitches yet</CardTitle>
            <CardDescription className="text-balance text-base">
              Pitches are drafted from completed investigations. Run one, then
              click <span className="font-medium">Draft pitch</span> on the
              report.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex justify-center pb-8">
            <Button
              render={<Link href="/investigations" />}
              nativeButton={false}
              size="lg"
            >
              See investigations
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {withPitch.map((r) => (
            <PitchRow key={r.id} r={r} />
          ))}
        </div>
      )}
    </div>
  );
}

function PitchRow({ r }: { r: InvestigationRow }) {
  const title =
    r.repo && r.issue_number ? `${r.repo}#${r.issue_number}` : "(pending)";
  // Truncate pitch preview to a sensible single-line excerpt.
  const preview = (r.pitch_md ?? "")
    .replace(/^#+\s.*$/gm, "") // strip headings from preview
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 240);

  return (
    <Card className="border-border/60 transition-colors hover:border-primary/40">
      <CardContent className="space-y-2 p-4">
        <div className="flex items-baseline justify-between gap-3">
          <div className="flex items-baseline gap-2 min-w-0">
            <span className="text-sm font-medium font-mono truncate">
              {title}
            </span>
            {r.issue_url && (
              <a
                href={r.issue_url}
                target="_blank"
                rel="noreferrer"
                className="text-muted-foreground hover:text-foreground"
                aria-label="Open issue on GitHub"
              >
                <ExternalLink className="size-3" />
              </a>
            )}
          </div>
          <Button
            render={<Link href={`/investigations/${r.id}`} />}
            nativeButton={false}
            variant="ghost"
            size="sm"
          >
            Open <ArrowRight className="ml-1 size-3.5" />
          </Button>
        </div>
        <p className="text-sm text-muted-foreground leading-relaxed line-clamp-3">
          {preview}…
        </p>
      </CardContent>
    </Card>
  );
}
