"use client";

import * as React from "react";
import { Copy, Loader2, RefreshCw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import type { PitchResponse } from "@/lib/api/types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ReportMarkdown } from "@/components/investigations/report-markdown";

type Props = {
  investigationId: string;
  /** Cached pitch already saved on the investigation row, if any. */
  initialPitch: string | null;
};

/**
 * Generates / regenerates the pitch comment. Posts to
 * /api/investigations/{id}/pitch, which returns the cached pitch on first
 * call (or regenerates with ?force=true on user request).
 */
export function PitchDrafter({ investigationId, initialPitch }: Props) {
  const [pitch, setPitch] = React.useState<PitchResponse | null>(
    initialPitch
      ? {
          investigation_id: investigationId,
          comment_md: initialPitch,
          asks_questions: initialPitch.includes("?"),
          estimated_timeline: null,
          tone: "respectful",
          cached: true,
        }
      : null,
  );
  const [pending, setPending] = React.useState(false);

  async function draft(force: boolean) {
    if (pending) return;
    setPending(true);
    const toastId = toast.loading(force ? "Regenerating pitch…" : "Drafting pitch…");
    try {
      const qs = force ? "?force=true" : "";
      const res = await fetch(
        `/api/investigations/${investigationId}/pitch${qs}`,
        { method: "POST", cache: "no-store" },
      );
      if (!res.ok) {
        const body = await res.text();
        throw new Error(body || `HTTP ${res.status}`);
      }
      const data = (await res.json()) as PitchResponse;
      setPitch(data);
      toast.success(
        data.cached ? "Loaded existing draft." : "Pitch drafted.",
        { id: toastId },
      );
    } catch (err) {
      toast.error("Pitch drafting failed.", {
        id: toastId,
        description: err instanceof Error ? err.message.slice(0, 200) : "",
      });
    } finally {
      setPending(false);
    }
  }

  async function copy() {
    if (!pitch) return;
    try {
      await navigator.clipboard.writeText(pitch.comment_md);
      toast.success("Copied to clipboard.");
    } catch {
      toast.error("Copy failed — select the text manually.");
    }
  }

  // First render with no pitch — show the kickoff button.
  if (!pitch) {
    return (
      <Card className="border-border/60 border-dashed">
        <CardContent className="flex flex-col items-start gap-3 p-5">
          <p className="text-sm text-muted-foreground">
            Ready to draft a comment you can post on the issue? The Pitch
            Writer agent will write something tone-guarded (no “generated by
            AI” vibes) based on the report above.
          </p>
          <Button onClick={() => draft(false)} disabled={pending}>
            {pending ? (
              <Loader2 className="mr-2 size-4 animate-spin" />
            ) : (
              <Sparkles className="mr-2 size-4" />
            )}
            {pending ? "Drafting…" : "Draft pitch"}
          </Button>
        </CardContent>
      </Card>
    );
  }

  // We have a pitch — show preview, copy, regenerate.
  const tags: string[] = [pitch.tone || "respectful"];
  if (pitch.estimated_timeline) tags.push(`timeline: ${pitch.estimated_timeline}`);
  if (pitch.asks_questions) tags.push("asks questions");
  if (pitch.cached) tags.push("cached");

  return (
    <Card className="border-border/60">
      <CardContent className="space-y-4 p-5">
        <div className="flex items-center justify-between gap-2">
          <div className="flex flex-wrap items-center gap-1.5">
            {tags.map((t) => (
              <Badge key={t} variant="secondary" className="font-normal">
                {t}
              </Badge>
            ))}
          </div>
          <div className="flex shrink-0 gap-2">
            <Button onClick={copy} variant="outline" size="sm">
              <Copy className="mr-2 size-3.5" /> Copy
            </Button>
            <Button
              onClick={() => draft(true)}
              variant="outline"
              size="sm"
              disabled={pending}
            >
              {pending ? (
                <Loader2 className="mr-2 size-3.5 animate-spin" />
              ) : (
                <RefreshCw className="mr-2 size-3.5" />
              )}
              Regenerate
            </Button>
          </div>
        </div>

        {/* Preview */}
        <div className="rounded-md border border-border/60 bg-background/50 p-4">
          <ReportMarkdown markdown={pitch.comment_md} />
        </div>

        {/* Raw markdown (for paste) */}
        <details className="group">
          <summary className="cursor-pointer text-xs text-muted-foreground hover:text-foreground transition-colors">
            Show raw markdown
          </summary>
          <pre className="mt-2 max-h-72 overflow-auto rounded-md bg-muted px-3 py-2 text-xs font-mono whitespace-pre-wrap">
            {pitch.comment_md}
          </pre>
        </details>
      </CardContent>
    </Card>
  );
}
